name: Rund autotests
on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: selec test to run
        required: true
        type: choice
        default: all
        options:
          - all

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Copy source code
        uses: actions/checkout@v4
      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Rund tests
        run: pytest -v
        
        
